project_name = "ds_251_RAG"

server = ''                   
database = ''          
schema = ''
table = ''  
# The above variables reference an example location in SQL Server, they will need to be changed for your project
# If you are using Databricks instead of SQL Server you will not need to set the 'server' variable
# Your project may use more than 1 table, you should add more table names and assignments as needed

# Here we describe where the output and logs are saved, change as necessary
output_dir = ''
log_dir = ''

DEV_MODE = true

PERSIST_DIRECTORY = "db"
EMBEDDING_MODEL = "sentence-transformers/all-mpnet-base-v2"